# ============================================================
#  BreadCost — JIRA Source Data
#  All epics and stories derived from work/120-task/JIRA.md
#  Structure: EPICS list + STORIES list
#
#  Epic keys: id, title, goal, sprint, requirements, release
#  Story keys: id, epic_id, title, acceptance_criteria (list),
#              priority, status, labels
# ============================================================

# ── PRIORITY MAP ────────────────────────────────────────────
# P0 = Highest, P1 = High, P2 = Medium, P3 = Low
PRIORITY_MAP = {
    "P0": "Highest",
    "P1": "High",
    "P2": "Medium",
    "P3": "Low",
}

# ── STATUS MAP ───────────────────────────────────────────────
# Maps JIRA.md status emoji to JIRA workflow status names
STATUS_MAP = {
    "✅ Done":    "Done",
    "🔄 In Progress": "In Progress",
    "📋 Planned": "To Do",
    "":           "To Do",
}

# ── EPICS ────────────────────────────────────────────────────
EPICS = [
    {
        "id": "BC-E00",
        "title": "User Journeys & End-to-End Flows",
        "goal": "Overarching reference epic. Documents all 62 named user flows (F1.1–F12.6) across all domains, cross-cutting all implementation epics. No code lives here — it is a traceability and alignment artifact.",
        "requirements": "All FRs across all domains",
        "release": "R1-R3",
        "labels": ["user-journey", "traceability"],
    },
    {
        "id": "BC-E01",
        "title": "Authentication & Authorization",
        "goal": "Secure login, JWT token management, and role enforcement across all endpoints.",
        "requirements": "FR-11.3, FR-11.4, NFR-G.4, NFR-G.5, NFR-G.6",
        "release": "R1",
        "labels": ["auth", "r1"],
    },
    {
        "id": "BC-E02",
        "title": "Order Management",
        "goal": "Full order lifecycle from creation through confirmation, cancellation, and status tracking.",
        "requirements": "FR-1.1, FR-1.6–FR-1.17",
        "release": "R1",
        "labels": ["orders", "r1"],
    },
    {
        "id": "BC-E03",
        "title": "Production Planning",
        "goal": "Plan creation, work order generation from confirmed orders, plan approval, and execution tracking.",
        "requirements": "FR-3.1–FR-3.10",
        "release": "R1",
        "labels": ["production", "r1"],
    },
    {
        "id": "BC-E04",
        "title": "Recipe & Product Management",
        "goal": "Recipe CRUD with versioning, ingredient management, technology steps, and product catalog.",
        "requirements": "FR-4.1–FR-4.9",
        "release": "R1",
        "labels": ["recipes", "products", "r1"],
    },
    {
        "id": "BC-E05",
        "title": "Inventory & Warehouse Management",
        "goal": "Lot-based receiving with FIFO cost tracking, transfers, adjustments, and stock alerts.",
        "requirements": "FR-5.1–FR-5.11",
        "release": "R1",
        "labels": ["inventory", "warehouse", "r1"],
    },
    {
        "id": "BC-E06",
        "title": "Point of Sale (POS)",
        "goal": "Walk-in B2C sales with cash/card payment, receipt data, and end-of-day reconciliation.",
        "requirements": "FR-8.1–FR-8.6",
        "release": "R1",
        "labels": ["pos", "r1"],
    },
    {
        "id": "BC-E07",
        "title": "Reporting & Dashboard",
        "goal": "Revenue summary, top products, production summary, and order summary for management decision-making.",
        "requirements": "FR-10.1, FR-10.4–FR-10.7",
        "release": "R1",
        "labels": ["reports", "dashboard", "r1"],
    },
    {
        "id": "BC-E08",
        "title": "User Management & Configuration",
        "goal": "Admin can manage staff accounts, roles, and tenant-wide settings.",
        "requirements": "FR-11.1–FR-11.9",
        "release": "R1",
        "labels": ["admin", "config", "r1"],
    },
    {
        "id": "BC-E09",
        "title": "Event Sourcing & Infrastructure",
        "goal": "All domain state changes recorded as immutable events with idempotency and CQRS projections.",
        "requirements": "NFR-G.10, NFR-G.11",
        "release": "R1",
        "labels": ["infrastructure", "event-sourcing", "r1"],
    },
    {
        "id": "BC-E10",
        "title": "Items & Raw Material Catalog",
        "goal": "Maintain a catalog of raw materials with units and stock thresholds.",
        "requirements": "FR-5.1",
        "release": "R1",
        "labels": ["items", "catalog", "r1"],
    },
    # ── Release 2 (planned) ───────────────────────────────
    {
        "id": "BC-E11",
        "title": "Customer Portal & Registration",
        "goal": "Web-based customer portal: registration, login, product catalog, order placement, real-time status.",
        "requirements": "FR-2.1–FR-2.5, FR-2.12",
        "release": "R2",
        "labels": ["customer-portal", "r2"],
    },
    {
        "id": "BC-E12",
        "title": "Loyalty Program",
        "goal": "Loyalty points, configurable tiers, tier benefits, point redemption at checkout.",
        "requirements": "FR-2.6–FR-2.11",
        "release": "R2",
        "labels": ["loyalty", "r2"],
    },
    {
        "id": "BC-E13",
        "title": "Supplier Management & PO Workflow",
        "goal": "Supplier catalog, PO suggestion, PO approval, Excel export, delivery matching, FX rates.",
        "requirements": "FR-6.1–FR-6.7",
        "release": "R2",
        "labels": ["suppliers", "procurement", "r2"],
    },
    {
        "id": "BC-E14",
        "title": "Delivery Management",
        "goal": "Delivery run assignment, manifests, driver completion, failed delivery, courier charges.",
        "requirements": "FR-7.1–FR-7.6",
        "release": "R2",
        "labels": ["delivery", "r2"],
    },
    {
        "id": "BC-E15",
        "title": "B2B Invoicing & Credit Control",
        "goal": "Invoices from delivered orders, payment terms, payment tracking, credit limit enforcement.",
        "requirements": "FR-9.8–FR-9.11",
        "release": "R2",
        "labels": ["invoicing", "finance", "r2"],
    },
    {
        "id": "BC-E16",
        "title": "Advanced Report Constructor",
        "goal": "User-configurable report builder with KPI blocks, advanced financial reports, export.",
        "requirements": "FR-10.2–FR-10.4",
        "release": "R2",
        "labels": ["reports", "r2"],
    },
    {
        "id": "BC-E17",
        "title": "Subscription Tier Management",
        "goal": "Super-admin assigns subscription tier per tenant; feature access enforced by tier.",
        "requirements": "FR-11.6–FR-11.7",
        "release": "R2",
        "labels": ["subscriptions", "r2"],
    },
    # ── Release 3 (planned) ───────────────────────────────
    {
        "id": "BC-E18",
        "title": "AI WhatsApp Order Intake",
        "goal": "Full AI-driven end-to-end WhatsApp order conversation: intent extraction, confirmation, upsell, conflict resolution.",
        "requirements": "FR-12.1, FR-12.2",
        "release": "R3",
        "labels": ["ai", "whatsapp", "r3"],
    },
    {
        "id": "BC-E19",
        "title": "AI Replenishment & Forecasting",
        "goal": "AI replenishment hints, production planning suggestions, and demand forecasting.",
        "requirements": "FR-12.3, FR-12.4, FR-12.7",
        "release": "R3",
        "labels": ["ai", "forecasting", "r3"],
    },
    {
        "id": "BC-E20",
        "title": "AI Pricing & Anomaly Alerts",
        "goal": "AI pricing suggestions and anomaly alerts in reports.",
        "requirements": "FR-12.5, FR-12.6",
        "release": "R3",
        "labels": ["ai", "pricing", "r3"],
    },
    {
        "id": "BC-E21",
        "title": "Driver Mobile App",
        "goal": "Driver app for real-time delivery tracking, packaging confirmation, on-spot payment collection.",
        "requirements": "FR-7.7, FR-8.7, FR-8.8",
        "release": "R3",
        "labels": ["mobile", "delivery", "r3"],
    },
    {
        "id": "BC-E22",
        "title": "Exchange Rate & Supplier API",
        "goal": "External exchange rate API and supplier API integrations.",
        "requirements": "FR-6.7, FR-9.7",
        "release": "R3",
        "labels": ["integrations", "r3"],
    },
    {
        "id": "BC-E23",
        "title": "Mobile Customer App",
        "goal": "iOS/Android customer app (mobile extension of the customer portal).",
        "requirements": "FR-2.1 (mobile)",
        "release": "R3",
        "labels": ["mobile", "customer-app", "r3"],
    },
]

# ── STORIES ──────────────────────────────────────────────────
STORIES = [
    # ── BC-E01: Auth ─────────────────────────────────────
    {
        "id": "BC-101",
        "epic_id": "BC-E01",
        "title": "User login with JWT",
        "acceptance_criteria": [
            "POST /v1/auth/login accepts {username, password}",
            "Returns JWT token, username, roles, tenantId",
            "Invalid credentials return 401",
            "Blank fields return 400",
        ],
        "priority": "P0",
        "status": "✅ Done",
        "labels": ["auth"],
    },
    {
        "id": "BC-102",
        "epic_id": "BC-E01",
        "title": "JWT authentication filter",
        "acceptance_criteria": [
            "All /v1/** endpoints require Bearer token",
            "Invalid/expired token returns 401",
            "Token contains username, roles, tenantId claims",
        ],
        "priority": "P0",
        "status": "✅ Done",
        "labels": ["auth"],
    },
    {
        "id": "BC-103",
        "epic_id": "BC-E01",
        "title": "Role-based method security",
        "acceptance_criteria": [
            "@PreAuthorize on every controller method",
            "Unauthorized role returns 403",
            "Matches role access matrix in MANUAL_TEST_PLAN.md Section 12",
        ],
        "priority": "P0",
        "status": "✅ Done",
        "labels": ["auth", "roles"],
    },
    {
        "id": "BC-104",
        "epic_id": "BC-E01",
        "title": "Password hashing with BCrypt",
        "acceptance_criteria": [
            "Passwords stored as BCrypt hashes",
            "Raw passwords never stored or logged",
        ],
        "priority": "P0",
        "status": "✅ Done",
        "labels": ["auth", "security"],
    },
    {
        "id": "BC-105",
        "epic_id": "BC-E01",
        "title": "Deactivated user cannot login",
        "acceptance_criteria": [
            "User with active=false receives 401 'Account is deactivated'",
        ],
        "priority": "P1",
        "status": "✅ Done",
        "labels": ["auth"],
    },
    # ── BC-E02: Orders ───────────────────────────────────
    {
        "id": "BC-201",
        "epic_id": "BC-E02",
        "title": "Create DRAFT order",
        "acceptance_criteria": [
            "POST /v1/orders creates order with status=DRAFT",
            "Requires tenantId, at least 1 line item",
            "Returns 201 with orderId",
            "Only Admin, ProductionUser can create",
        ],
        "priority": "P0",
        "status": "✅ Done",
        "labels": ["orders"],
    },
    {
        "id": "BC-202",
        "epic_id": "BC-E02",
        "title": "List orders with filters",
        "acceptance_criteria": [
            "GET /v1/orders?tenantId=&status= returns array",
            "Filters by status, customerId",
            "Empty filters return all",
            "Role-restricted",
        ],
        "priority": "P0",
        "status": "✅ Done",
        "labels": ["orders"],
    },
    {
        "id": "BC-203",
        "epic_id": "BC-E02",
        "title": "Get order by ID",
        "acceptance_criteria": [
            "GET /v1/orders/{id}?tenantId= returns full order with lines",
            "404 if not found",
        ],
        "priority": "P1",
        "status": "✅ Done",
        "labels": ["orders"],
    },
    {
        "id": "BC-204",
        "epic_id": "BC-E02",
        "title": "Confirm order (DRAFT→CONFIRMED)",
        "acceptance_criteria": [
            "POST /v1/orders/{id}/confirm transitions DRAFT→CONFIRMED",
            "Sets confirmedAt timestamp",
            "Emits OrderConfirmedEvent",
            "Rejects non-DRAFT orders with 409",
        ],
        "priority": "P0",
        "status": "✅ Done",
        "labels": ["orders", "state-machine"],
    },
    {
        "id": "BC-205",
        "epic_id": "BC-E02",
        "title": "Cancel order",
        "acceptance_criteria": [
            "POST /v1/orders/{id}/cancel?reason= transitions to CANCELLED",
            "Requires reason parameter",
            "Only cancellable from DRAFT or CONFIRMED",
            "Emits OrderCancelledEvent",
        ],
        "priority": "P0",
        "status": "✅ Done",
        "labels": ["orders", "state-machine"],
    },
    {
        "id": "BC-206",
        "epic_id": "BC-E02",
        "title": "Status transition enforcement",
        "acceptance_criteria": [
            "Invalid transitions (e.g. CANCELLED→CONFIRMED) return 409",
            "Double-confirm returns 409",
        ],
        "priority": "P0",
        "status": "✅ Done",
        "labels": ["orders", "state-machine"],
    },
    {
        "id": "BC-207",
        "epic_id": "BC-E02",
        "title": "Rush order support",
        "acceptance_criteria": [
            "forceRush=true creates rush order",
            "Custom premium % can be set via customRushPremiumPct",
        ],
        "priority": "P2",
        "status": "✅ Done",
        "labels": ["orders", "rush"],
    },
    {
        "id": "BC-208",
        "epic_id": "BC-E02",
        "title": "Order status advance",
        "acceptance_criteria": [
            "POST /v1/orders/{id}/status?targetStatus= advances order (IN_PRODUCTION, READY, DELIVERED)",
        ],
        "priority": "P1",
        "status": "✅ Done",
        "labels": ["orders", "state-machine"],
    },
    # ── BC-E03: Production Planning ──────────────────────
    {
        "id": "BC-301",
        "epic_id": "BC-E03",
        "title": "Create production plan",
        "acceptance_criteria": [
            "POST /v1/production-plans with date, shift, tenantId",
            "Returns 201 with planId, status=DRAFT",
        ],
        "priority": "P0",
        "status": "✅ Done",
        "labels": ["production"],
    },
    {
        "id": "BC-302",
        "epic_id": "BC-E03",
        "title": "Generate work orders",
        "acceptance_criteria": [
            "POST /plans/{id}/generate creates WOs from confirmed orders",
            "Plan status → GENERATED",
            "Each WO has product, target qty, department",
        ],
        "priority": "P0",
        "status": "✅ Done",
        "labels": ["production"],
    },
    {
        "id": "BC-303",
        "epic_id": "BC-E03",
        "title": "Approve plan",
        "acceptance_criteria": [
            "POST /plans/{id}/approve transitions GENERATED→APPROVED",
            "Only Admin, ProductionUser can approve",
        ],
        "priority": "P0",
        "status": "✅ Done",
        "labels": ["production"],
    },
    {
        "id": "BC-304",
        "epic_id": "BC-E03",
        "title": "Start and complete plan lifecycle",
        "acceptance_criteria": [
            "Start: APPROVED→IN_PROGRESS",
            "Complete: IN_PROGRESS→COMPLETED",
        ],
        "priority": "P1",
        "status": "✅ Done",
        "labels": ["production", "state-machine"],
    },
    {
        "id": "BC-305",
        "epic_id": "BC-E03",
        "title": "Work order lifecycle",
        "acceptance_criteria": [
            "Start WO: PLANNED→IN_PROGRESS",
            "Complete WO: IN_PROGRESS→COMPLETED",
            "Cancel WO: any→CANCELLED",
        ],
        "priority": "P0",
        "status": "✅ Done",
        "labels": ["production", "state-machine"],
    },
    {
        "id": "BC-306",
        "epic_id": "BC-E03",
        "title": "Material requirements view",
        "acceptance_criteria": [
            "GET /plans/{id}/material-requirements returns ingredient needs based on recipes",
        ],
        "priority": "P2",
        "status": "✅ Done",
        "labels": ["production", "inventory"],
    },
    {
        "id": "BC-307",
        "epic_id": "BC-E03",
        "title": "Plan schedule and WO scheduling",
        "acceptance_criteria": [
            "GET /plans/{id}/schedule returns timeline",
            "PATCH /work-orders/{id}/schedule adjusts start/duration",
        ],
        "priority": "P2",
        "status": "✅ Done",
        "labels": ["production"],
    },
    {
        "id": "BC-308",
        "epic_id": "BC-E03",
        "title": "List work orders by department",
        "acceptance_criteria": [
            "GET /work-orders?tenantId=&departmentId= returns filtered WOs",
        ],
        "priority": "P1",
        "status": "✅ Done",
        "labels": ["production"],
    },
    # ── BC-E04: Recipe & Product ─────────────────────────
    {
        "id": "BC-401",
        "epic_id": "BC-E04",
        "title": "Create recipe with ingredients",
        "acceptance_criteria": [
            "POST /v1/recipes with ingredients array",
            "Returns 201 with version number",
            "Only Admin, Technologist can create",
        ],
        "priority": "P0",
        "status": "✅ Done",
        "labels": ["recipes"],
    },
    {
        "id": "BC-402",
        "epic_id": "BC-E04",
        "title": "Recipe versioning",
        "acceptance_criteria": [
            "Multiple recipes per product, each with version number",
            "GET /v1/recipes?productId= returns version history",
        ],
        "priority": "P1",
        "status": "✅ Done",
        "labels": ["recipes"],
    },
    {
        "id": "BC-403",
        "epic_id": "BC-E04",
        "title": "Activate recipe",
        "acceptance_criteria": [
            "POST /recipes/{id}/activate sets as active for product",
            "Archives previous active version",
        ],
        "priority": "P0",
        "status": "✅ Done",
        "labels": ["recipes"],
    },
    {
        "id": "BC-404",
        "epic_id": "BC-E04",
        "title": "Get active recipe",
        "acceptance_criteria": [
            "GET /v1/recipes/active?productId= returns current active recipe",
        ],
        "priority": "P1",
        "status": "✅ Done",
        "labels": ["recipes"],
    },
    {
        "id": "BC-405",
        "epic_id": "BC-E04",
        "title": "Update recipe ingredients",
        "acceptance_criteria": [
            "PUT /recipes/{id}/ingredients replaces ingredient list",
        ],
        "priority": "P1",
        "status": "✅ Done",
        "labels": ["recipes"],
    },
    {
        "id": "BC-406",
        "epic_id": "BC-E04",
        "title": "Material requirements calculation",
        "acceptance_criteria": [
            "GET /recipes/{id}/material-requirements?batchMultiplier= returns per-ingredient quantities needed",
        ],
        "priority": "P2",
        "status": "✅ Done",
        "labels": ["recipes", "inventory"],
    },
    {
        "id": "BC-407",
        "epic_id": "BC-E04",
        "title": "Technology steps CRUD",
        "acceptance_criteria": [
            "Create step: POST /v1/technology-steps",
            "Edit: PUT /technology-steps/{id}",
            "Delete: DELETE /technology-steps/{id}",
            "List: GET /technology-steps?recipeId= ordered by stepNumber",
        ],
        "priority": "P1",
        "status": "✅ Done",
        "labels": ["recipes", "tech-steps"],
    },
    {
        "id": "BC-408",
        "epic_id": "BC-E04",
        "title": "Product CRUD",
        "acceptance_criteria": [
            "List: GET /v1/products",
            "Create: POST /v1/products (201)",
            "Update: PUT /products/{id}",
            "Sale unit: PIECE/WEIGHT/BOTH",
        ],
        "priority": "P0",
        "status": "✅ Done",
        "labels": ["products"],
    },
    # ── BC-E05: Inventory ────────────────────────────────
    {
        "id": "BC-501",
        "epic_id": "BC-E05",
        "title": "Receive lot (stock receipt)",
        "acceptance_criteria": [
            "POST /v1/inventory/receipts records lot with cost",
            "Emits ReceiveLotEvent",
            "Idempotent via idempotencyKey",
            "Only Admin, Warehouse can receive",
        ],
        "priority": "P0",
        "status": "✅ Done",
        "labels": ["inventory"],
    },
    {
        "id": "BC-502",
        "epic_id": "BC-E05",
        "title": "View inventory positions",
        "acceptance_criteria": [
            "GET /v1/inventory/positions returns on-hand qty per item per site",
            "Filter by siteId",
        ],
        "priority": "P0",
        "status": "✅ Done",
        "labels": ["inventory"],
    },
    {
        "id": "BC-503",
        "epic_id": "BC-E05",
        "title": "Inventory transfer",
        "acceptance_criteria": [
            "POST /v1/inventory/transfers moves qty between locations",
            "Emits TransferInventoryEvent",
            "Idempotent",
        ],
        "priority": "P1",
        "status": "✅ Done",
        "labels": ["inventory"],
    },
    {
        "id": "BC-504",
        "epic_id": "BC-E05",
        "title": "Inventory adjustment",
        "acceptance_criteria": [
            "POST /v1/inventory/adjust with reason code (WASTE/SPOILAGE/COUNT_CORRECTION/OTHER)",
            "Positive or negative qty",
        ],
        "priority": "P1",
        "status": "✅ Done",
        "labels": ["inventory"],
    },
    {
        "id": "BC-505",
        "epic_id": "BC-E05",
        "title": "Issue to batch (material consumption)",
        "acceptance_criteria": [
            "POST /v1/batches/{id}/issues issues material to production batch",
            "FIFO lot selection",
            "Emits IssueToBatchEvent",
        ],
        "priority": "P0",
        "status": "✅ Done",
        "labels": ["inventory", "production"],
    },
    {
        "id": "BC-506",
        "epic_id": "BC-E05",
        "title": "Stock alerts",
        "acceptance_criteria": [
            "GET /v1/inventory/alerts returns items below minStockThreshold",
            "Each alert: itemId, onHandQty, minThreshold, severity",
        ],
        "priority": "P1",
        "status": "✅ Done",
        "labels": ["inventory", "alerts"],
    },
    {
        "id": "BC-507",
        "epic_id": "BC-E05",
        "title": "Idempotency enforcement",
        "acceptance_criteria": [
            "Resending receipt/transfer with same idempotencyKey does not duplicate",
            "Returns success without re-processing",
        ],
        "priority": "P0",
        "status": "✅ Done",
        "labels": ["inventory", "idempotency"],
    },
    # ── BC-E06: POS ──────────────────────────────────────
    {
        "id": "BC-601",
        "epic_id": "BC-E06",
        "title": "Create POS sale (CASH)",
        "acceptance_criteria": [
            "POST /v1/pos/sales with paymentMethod=CASH",
            "Calculates totalAmount, changeGiven",
            "Returns 201 with saleId, status=COMPLETED",
            "Records cashierId from JWT",
        ],
        "priority": "P0",
        "status": "✅ Done",
        "labels": ["pos"],
    },
    {
        "id": "BC-602",
        "epic_id": "BC-E06",
        "title": "Create POS sale (CARD)",
        "acceptance_criteria": [
            "paymentMethod=CARD, cardReference required",
            "changeGiven=0",
            "Returns 201",
        ],
        "priority": "P0",
        "status": "✅ Done",
        "labels": ["pos"],
    },
    {
        "id": "BC-603",
        "epic_id": "BC-E06",
        "title": "List POS sales",
        "acceptance_criteria": [
            "GET /v1/pos/sales?tenantId= returns sale history",
            "Filter by date",
        ],
        "priority": "P1",
        "status": "✅ Done",
        "labels": ["pos"],
    },
    {
        "id": "BC-604",
        "epic_id": "BC-E06",
        "title": "End-of-day reconciliation",
        "acceptance_criteria": [
            "POST /v1/pos/reconcile returns cash/card totals, refunds, net sales",
            "Grouped by date",
        ],
        "priority": "P1",
        "status": "✅ Done",
        "labels": ["pos"],
    },
    {
        "id": "BC-605",
        "epic_id": "BC-E06",
        "title": "POS input validation",
        "acceptance_criteria": [
            "Empty lines → 400",
            "Missing payment method → 400",
        ],
        "priority": "P1",
        "status": "✅ Done",
        "labels": ["pos"],
    },
    {
        "id": "BC-606",
        "epic_id": "BC-E06",
        "title": "POS role enforcement",
        "acceptance_criteria": [
            "Only Admin, Cashier can create sales",
            "Warehouse, Finance, Production → 403",
        ],
        "priority": "P0",
        "status": "✅ Done",
        "labels": ["pos", "roles"],
    },
    # ── BC-E07: Reports ──────────────────────────────────
    {
        "id": "BC-701",
        "epic_id": "BC-E07",
        "title": "Revenue summary report",
        "acceptance_criteria": [
            "GET /reports/revenue-summary returns today/week/month/allTime revenue",
            "Includes currency",
            "Accessible to Admin, FinanceUser, Viewer",
        ],
        "priority": "P0",
        "status": "✅ Done",
        "labels": ["reports"],
    },
    {
        "id": "BC-702",
        "epic_id": "BC-E07",
        "title": "Top products report",
        "acceptance_criteria": [
            "GET /reports/top-products?limit=N returns ranked products",
            "Each entry: productName, totalQty, totalRevenue",
        ],
        "priority": "P1",
        "status": "✅ Done",
        "labels": ["reports"],
    },
    {
        "id": "BC-703",
        "epic_id": "BC-E07",
        "title": "Production summary report",
        "acceptance_criteria": [
            "GET /reports/production-summary returns plan counts by status, WO completion rate",
            "Date range filter supported",
        ],
        "priority": "P1",
        "status": "✅ Done",
        "labels": ["reports"],
    },
    {
        "id": "BC-704",
        "epic_id": "BC-E07",
        "title": "Orders summary report",
        "acceptance_criteria": [
            "GET /reports/orders-summary returns today count, value, breakdown by status",
        ],
        "priority": "P1",
        "status": "✅ Done",
        "labels": ["reports"],
    },
    {
        "id": "BC-705",
        "epic_id": "BC-E07",
        "title": "Report role enforcement",
        "acceptance_criteria": [
            "Admin, FinanceUser, Viewer can access",
            "Cashier → 403",
        ],
        "priority": "P0",
        "status": "✅ Done",
        "labels": ["reports", "roles"],
    },
    # ── BC-E08: Admin & Config ───────────────────────────
    {
        "id": "BC-801",
        "epic_id": "BC-E08",
        "title": "List users",
        "acceptance_criteria": [
            "GET /v1/users?tenantId= returns user list",
            "Password hashes masked",
            "Admin only",
        ],
        "priority": "P0",
        "status": "✅ Done",
        "labels": ["admin", "users"],
    },
    {
        "id": "BC-802",
        "epic_id": "BC-E08",
        "title": "Create user",
        "acceptance_criteria": [
            "POST /v1/users with username, password, roles",
            "Returns 201",
            "New user can log in",
            "Duplicate username → 409",
        ],
        "priority": "P0",
        "status": "✅ Done",
        "labels": ["admin", "users"],
    },
    {
        "id": "BC-803",
        "epic_id": "BC-E08",
        "title": "Update user roles",
        "acceptance_criteria": [
            "PUT /v1/users/{id} updates roles, displayName, department",
            "Changes take effect on next login",
        ],
        "priority": "P1",
        "status": "✅ Done",
        "labels": ["admin", "users", "roles"],
    },
    {
        "id": "BC-804",
        "epic_id": "BC-E08",
        "title": "Deactivate user",
        "acceptance_criteria": [
            "PUT /v1/users/{id} with active:false",
            "Deactivated user cannot log in (401)",
        ],
        "priority": "P1",
        "status": "✅ Done",
        "labels": ["admin", "users"],
    },
    {
        "id": "BC-805",
        "epic_id": "BC-E08",
        "title": "Reset password",
        "acceptance_criteria": [
            "POST /v1/users/{id}/reset-password",
            "Old password stops working, new one works",
        ],
        "priority": "P1",
        "status": "✅ Done",
        "labels": ["admin", "users"],
    },
    {
        "id": "BC-806",
        "epic_id": "BC-E08",
        "title": "Department CRUD",
        "acceptance_criteria": [
            "Create: POST /v1/departments (201)",
            "List: GET /v1/departments",
            "Update: PUT /departments/{id}",
            "Admin only",
        ],
        "priority": "P1",
        "status": "✅ Done",
        "labels": ["admin", "departments"],
    },
    {
        "id": "BC-807",
        "epic_id": "BC-E08",
        "title": "Tenant config management",
        "acceptance_criteria": [
            "GET /v1/config returns cutoff time, rush premium, currency",
            "PUT /v1/config updates settings",
            "Admin only for writes",
        ],
        "priority": "P1",
        "status": "✅ Done",
        "labels": ["admin", "config"],
    },
    # ── BC-E09: Event Sourcing ───────────────────────────
    {
        "id": "BC-901",
        "epic_id": "BC-E09",
        "title": "Event store implementation",
        "acceptance_criteria": [
            "Append-only event store",
            "Events: ReceiveLot, IssueToBatch, TransferInventory, OrderCreated/Confirmed/Cancelled, CloseBatch, etc.",
            "Each event has idempotencyKey, occurredAtUtc, tenantId",
        ],
        "priority": "P0",
        "status": "✅ Done",
        "labels": ["infrastructure", "event-sourcing"],
    },
    {
        "id": "BC-902",
        "epic_id": "BC-E09",
        "title": "Idempotency service",
        "acceptance_criteria": [
            "Duplicate idempotencyKey detected and rejected",
            "Command handler returns success without re-executing",
        ],
        "priority": "P0",
        "status": "✅ Done",
        "labels": ["infrastructure", "idempotency"],
    },
    {
        "id": "BC-903",
        "epic_id": "BC-E09",
        "title": "Inventory projection",
        "acceptance_criteria": [
            "Reads events to build on-hand positions",
            "FIFO cost layers maintained per lot",
        ],
        "priority": "P0",
        "status": "✅ Done",
        "labels": ["infrastructure", "inventory"],
    },
    {
        "id": "BC-904",
        "epic_id": "BC-E09",
        "title": "Global exception handler",
        "acceptance_criteria": [
            "IllegalArgumentException → 400",
            "AccessDeniedException → 403",
            "IllegalStateException → 409",
            "DataIntegrityViolationException → 409",
            "Unhandled → 500",
        ],
        "priority": "P0",
        "status": "✅ Done",
        "labels": ["infrastructure"],
    },
    # ── BC-E10: Items ────────────────────────────────────
    {
        "id": "BC-1001",
        "epic_id": "BC-E10",
        "title": "Item CRUD",
        "acceptance_criteria": [
            "Create: POST /v1/items (201)",
            "List: GET /v1/items?type=&activeOnly=",
            "Update: PUT /items/{id}",
            "Fields: name, type, baseUom, minStockThreshold",
        ],
        "priority": "P0",
        "status": "✅ Done",
        "labels": ["items"],
    },
    {
        "id": "BC-1002",
        "epic_id": "BC-E10",
        "title": "Item types",
        "acceptance_criteria": [
            "Supports INGREDIENT, PACKAGING, FG, BYPRODUCT, WIP",
            "Filter by type query param",
        ],
        "priority": "P1",
        "status": "✅ Done",
        "labels": ["items"],
    },

    # ══════════════════════════════════════════════════════
    #  RELEASE 2 — Growth
    # ══════════════════════════════════════════════════════

    # ── BC-E02 R2 additions: WhatsApp partial (FR-1.2–1.5) ─
    {
        "id": "BC-209",
        "epic_id": "BC-E02",
        "release": "R2",
        "title": "WhatsApp message to draft order (operator review)",
        "acceptance_criteria": [
            "Incoming WhatsApp text parsed into a draft order",
            "Draft presented to operator for review before confirmation",
            "Operator can edit, confirm, or discard the draft",
            "FR-1.2 satisfied",
        ],
        "priority": "P1",
        "status": "📋 Planned",
        "labels": ["orders", "whatsapp"],
    },
    {
        "id": "BC-210",
        "epic_id": "BC-E02",
        "release": "R2",
        "title": "AI bot two-way WhatsApp conversation",
        "acceptance_criteria": [
            "Bot conducts multi-turn conversation to confirm order details",
            "Suggests upsells (configurable per customer — off by default)",
            "Handles modifications and re-confirmation",
            "FR-1.3 and FR-1.4 satisfied",
        ],
        "priority": "P1",
        "status": "📋 Planned",
        "labels": ["orders", "whatsapp", "ai"],
    },
    {
        "id": "BC-211",
        "epic_id": "BC-E02",
        "release": "R2",
        "title": "Human escalation from WhatsApp conversation",
        "acceptance_criteria": [
            "Customer request for human triggers in-app alert + WhatsApp notification to assigned operator",
            "Bot pauses conversation and hands off",
            "FR-1.5 satisfied",
        ],
        "priority": "P2",
        "status": "📋 Planned",
        "labels": ["orders", "whatsapp"],
    },

    # ── BC-E11: Customer Portal ──────────────────────────
    {
        "id": "BC-1101",
        "epic_id": "BC-E11",
        "release": "R2",
        "title": "Customer registration",
        "acceptance_criteria": [
            "POST /v2/customers/register with name, email, phone, delivery address(es)",
            "Returns 201 with customerId",
            "Duplicate email → 409",
            "FR-2.2 satisfied",
        ],
        "priority": "P0",
        "status": "� In Progress",
        "labels": ["customer-portal"],
    },
    {
        "id": "BC-1102",
        "epic_id": "BC-E11",
        "release": "R2",
        "title": "Customer login and profile management",
        "acceptance_criteria": [
            "POST /v2/customers/login returns JWT",
            "GET/PUT /v2/customers/me for profile and address updates",
            "Secure password hashing",
            "FR-2.3 satisfied",
        ],
        "priority": "P0",
        "status": "📋 Planned",
        "labels": ["customer-portal", "auth"],
    },
    {
        "id": "BC-1103",
        "epic_id": "BC-E11",
        "release": "R2",
        "title": "Customer-facing product catalog",
        "acceptance_criteria": [
            "GET /v2/catalog returns products with customer-specific prices",
            "Global price list applied unless customer override exists",
            "Catalog loads within 3 seconds",
            "FR-2.4 satisfied",
        ],
        "priority": "P0",
        "status": "📋 Planned",
        "labels": ["customer-portal", "products"],
    },
    {
        "id": "BC-1104",
        "epic_id": "BC-E11",
        "release": "R2",
        "title": "Place order via customer portal",
        "acceptance_criteria": [
            "POST /v2/customer-orders creates order subject to cutoff and lead time rules",
            "Lead time conflicts presented per line item",
            "Customer accepts or drops conflicting items",
            "FR-2.5 satisfied",
        ],
        "priority": "P0",
        "status": "📋 Planned",
        "labels": ["customer-portal", "orders"],
    },
    {
        "id": "BC-1105",
        "epic_id": "BC-E11",
        "release": "R2",
        "title": "Real-time order status and order history",
        "acceptance_criteria": [
            "GET /v2/customer-orders returns order history with statuses",
            "Active order status is real-time (polling or push)",
            "Full order details including invoice info",
            "FR-2.11 and FR-2.12 satisfied",
        ],
        "priority": "P1",
        "status": "📋 Planned",
        "labels": ["customer-portal", "orders"],
    },

    # ── BC-E12: Loyalty Program ──────────────────────────
    {
        "id": "BC-1201",
        "epic_id": "BC-E12",
        "release": "R2",
        "title": "Award loyalty points on completed purchase",
        "acceptance_criteria": [
            "Points awarded automatically when order status → DELIVERED",
            "Configurable earning rate (points per currency unit)",
            "No points for cancelled or refunded orders",
            "FR-2.6 satisfied",
        ],
        "priority": "P1",
        "status": "📋 Planned",
        "labels": ["loyalty"],
    },
    {
        "id": "BC-1202",
        "epic_id": "BC-E12",
        "release": "R2",
        "title": "Configurable loyalty tiers",
        "acceptance_criteria": [
            "Admin can define tiers: name, point threshold, rush order threshold",
            "Tier advancement calculated automatically on point update",
            "FR-2.7 satisfied",
        ],
        "priority": "P1",
        "status": "📋 Planned",
        "labels": ["loyalty"],
    },
    {
        "id": "BC-1203",
        "epic_id": "BC-E12",
        "release": "R2",
        "title": "Tier benefits management",
        "acceptance_criteria": [
            "Admin configures benefits per tier: discount %, free items, priority flag",
            "Benefits applied automatically at order creation",
            "FR-2.8 satisfied",
        ],
        "priority": "P2",
        "status": "📋 Planned",
        "labels": ["loyalty"],
    },
    {
        "id": "BC-1204",
        "epic_id": "BC-E12",
        "release": "R2",
        "title": "Redeem loyalty points at checkout",
        "acceptance_criteria": [
            "Customer can apply points at checkout — reduces order total",
            "Point value configurable (e.g., 100 points = $1)",
            "Partial redemption supported",
            "FR-2.9 satisfied",
        ],
        "priority": "P1",
        "status": "📋 Planned",
        "labels": ["loyalty"],
    },
    {
        "id": "BC-1205",
        "epic_id": "BC-E12",
        "release": "R2",
        "title": "Points balance and history view",
        "acceptance_criteria": [
            "GET /v2/loyalty/me returns balance, tier, and transaction history",
            "History shows: date, order ID, points earned/spent, running balance",
            "FR-2.10 satisfied",
        ],
        "priority": "P1",
        "status": "📋 Planned",
        "labels": ["loyalty"],
    },
    {
        "id": "BC-1206",
        "epic_id": "BC-E12",
        "release": "R2",
        "title": "Loyalty tier rule configuration UI",
        "acceptance_criteria": [
            "Admin UI: create/edit/delete tiers, set thresholds and benefits",
            "Changes take effect immediately without restart",
            "FR-2.7 and FR-2.8 UI satisfied",
        ],
        "priority": "P2",
        "status": "📋 Planned",
        "labels": ["loyalty", "admin"],
    },

    # ── BC-E13: Supplier Management ──────────────────────
    {
        "id": "BC-1301",
        "epic_id": "BC-E13",
        "release": "R2",
        "title": "Supplier catalog CRUD",
        "acceptance_criteria": [
            "Create: POST /v2/suppliers with name, contact, items supplied, price per item, lead time",
            "List: GET /v2/suppliers",
            "Update: PUT /v2/suppliers/{id}",
            "Delete (deactivate): DELETE /v2/suppliers/{id}",
            "FR-6.1 satisfied",
        ],
        "priority": "P0",
        "status": "📋 Planned",
        "labels": ["suppliers"],
    },
    {
        "id": "BC-1302",
        "epic_id": "BC-E13",
        "release": "R2",
        "title": "PO suggestion generation",
        "acceptance_criteria": [
            "System generates PO suggestions when stock falls below minimum threshold",
            "Suggestion uses consumption rate × lead time to calculate quantity",
            "GET /v2/po-suggestions lists pending suggestions per supplier",
            "FR-6.2 satisfied",
        ],
        "priority": "P0",
        "status": "📋 Planned",
        "labels": ["suppliers", "procurement"],
    },
    {
        "id": "BC-1303",
        "epic_id": "BC-E13",
        "release": "R2",
        "title": "PO review and approval",
        "acceptance_criteria": [
            "Manager can adjust quantities on a suggestion before approving",
            "POST /v2/purchase-orders/{id}/approve transitions to APPROVED",
            "Approval logged in audit trail",
            "FR-6.3 satisfied",
        ],
        "priority": "P0",
        "status": "📋 Planned",
        "labels": ["suppliers", "procurement"],
    },
    {
        "id": "BC-1304",
        "epic_id": "BC-E13",
        "release": "R2",
        "title": "PO Excel export",
        "acceptance_criteria": [
            "GET /v2/purchase-orders/{id}/export?format=xlsx",
            "Formatted Excel file with supplier details, items, quantities, total",
            "Completes within 5 seconds",
            "FR-6.4 satisfied",
        ],
        "priority": "P1",
        "status": "📋 Planned",
        "labels": ["suppliers", "procurement"],
    },
    {
        "id": "BC-1305",
        "epic_id": "BC-E13",
        "release": "R2",
        "title": "Delivery matching against PO",
        "acceptance_criteria": [
            "On inventory receipt, system matches against open PO by supplier + items",
            "Discrepancies (quantity, item, price) flagged for review",
            "Matched PO transitions to DELIVERED",
            "FR-6.5 satisfied",
        ],
        "priority": "P1",
        "status": "📋 Planned",
        "labels": ["suppliers", "inventory"],
    },
    {
        "id": "BC-1306",
        "epic_id": "BC-E13",
        "release": "R2",
        "title": "FX rate per purchase transaction",
        "acceptance_criteria": [
            "Receipt endpoint accepts currency + exchangeRateToMain",
            "Amount stored in both original currency and main currency",
            "FR-6.6 satisfied",
        ],
        "priority": "P1",
        "status": "📋 Planned",
        "labels": ["suppliers", "finance"],
    },

    # ── BC-E14: Delivery Management ──────────────────────
    {
        "id": "BC-1401",
        "epic_id": "BC-E14",
        "release": "R2",
        "title": "Assign orders to delivery runs",
        "acceptance_criteria": [
            "POST /v2/delivery-runs assigns confirmed orders by delivery window + driver",
            "Each run has a driver, vehicle, and scheduled time",
            "FR-7.1 satisfied",
        ],
        "priority": "P0",
        "status": "📋 Planned",
        "labels": ["delivery"],
    },
    {
        "id": "BC-1402",
        "epic_id": "BC-E14",
        "release": "R2",
        "title": "Delivery manifest generation",
        "acceptance_criteria": [
            "GET /v2/delivery-runs/{id}/manifest returns manifest PDF/JSON",
            "Manifest includes: orders, customers, addresses, items, quantities",
            "Printable/exportable",
            "FR-7.2 satisfied",
        ],
        "priority": "P0",
        "status": "📋 Planned",
        "labels": ["delivery"],
    },
    {
        "id": "BC-1403",
        "epic_id": "BC-E14",
        "release": "R2",
        "title": "Mark delivery completed",
        "acceptance_criteria": [
            "POST /v2/deliveries/{id}/complete transitions order to DELIVERED",
            "Records completedAt timestamp and operator ID",
            "FR-7.3 satisfied",
        ],
        "priority": "P0",
        "status": "📋 Planned",
        "labels": ["delivery"],
    },
    {
        "id": "BC-1404",
        "epic_id": "BC-E14",
        "release": "R2",
        "title": "Failed delivery recording and re-delivery workflow",
        "acceptance_criteria": [
            "POST /v2/deliveries/{id}/fail with mandatory reason",
            "Triggers return or re-delivery workflow option",
            "Order status set to DELIVERY_FAILED",
            "FR-7.4 satisfied",
        ],
        "priority": "P1",
        "status": "📋 Planned",
        "labels": ["delivery"],
    },
    {
        "id": "BC-1405",
        "epic_id": "BC-E14",
        "release": "R2",
        "title": "Split delivery courier charge calculation",
        "acceptance_criteria": [
            "When customer opts for split delivery, courier charge calculated and applied to secondary delivery",
            "Charge shown to customer before confirmation",
            "FR-7.5 satisfied",
        ],
        "priority": "P1",
        "status": "📋 Planned",
        "labels": ["delivery", "orders"],
    },
    {
        "id": "BC-1406",
        "epic_id": "BC-E14",
        "release": "R2",
        "title": "Courier charge waiver with authorization",
        "acceptance_criteria": [
            "POST /v2/deliveries/{id}/waive-charge requires Manager role",
            "Waiver logged in audit trail with actor + timestamp",
            "FR-7.6 satisfied",
        ],
        "priority": "P2",
        "status": "📋 Planned",
        "labels": ["delivery", "finance"],
    },

    # ── BC-E15: B2B Invoicing & Credit ───────────────────
    {
        "id": "BC-1501",
        "epic_id": "BC-E15",
        "release": "R2",
        "title": "Generate invoice from delivered order",
        "acceptance_criteria": [
            "Invoice auto-generated when order status → DELIVERED",
            "Invoice includes: line items, totals, customer info, payment due date",
            "FR-9.8 satisfied",
        ],
        "priority": "P0",
        "status": "📋 Planned",
        "labels": ["invoicing"],
    },
    {
        "id": "BC-1502",
        "epic_id": "BC-E15",
        "release": "R2",
        "title": "Payment terms per customer",
        "acceptance_criteria": [
            "Admin can set payment terms per customer: net7/net14/net30",
            "Due date calculated at invoice generation from terms",
            "FR-9.8 satisfied",
        ],
        "priority": "P0",
        "status": "📋 Planned",
        "labels": ["invoicing", "finance"],
    },
    {
        "id": "BC-1503",
        "epic_id": "BC-E15",
        "release": "R2",
        "title": "Invoice payment status tracking",
        "acceptance_criteria": [
            "Statuses: UNPAID, PARTIALLY_PAID, PAID, OVERDUE",
            "POST /v2/invoices/{id}/payment records payment amount",
            "Status transitions automatically based on payments + due date",
            "FR-9.9 satisfied",
        ],
        "priority": "P0",
        "status": "📋 Planned",
        "labels": ["invoicing", "finance"],
    },
    {
        "id": "BC-1504",
        "epic_id": "BC-E15",
        "release": "R2",
        "title": "Credit limit enforcement and overdue order block",
        "acceptance_criteria": [
            "New order blocked if customer outstanding balance > credit limit",
            "New order blocked if any invoice overdue by > configurable days",
            "Finance role alerted via in-app notification",
            "FR-9.10 satisfied",
        ],
        "priority": "P1",
        "status": "📋 Planned",
        "labels": ["invoicing", "finance", "orders"],
    },
    {
        "id": "BC-1505",
        "epic_id": "BC-E15",
        "release": "R2",
        "title": "Customer-specific pricing and discount rules",
        "acceptance_criteria": [
            "Admin can set per-customer price overrides per product",
            "Applied at order creation — overrides global price list",
            "Price history retained and auditable",
            "FR-9.11 satisfied",
        ],
        "priority": "P1",
        "status": "📋 Planned",
        "labels": ["invoicing", "orders"],
    },

    # ── BC-E16: Advanced Report Constructor ──────────────
    {
        "id": "BC-1601",
        "epic_id": "BC-E16",
        "release": "R2",
        "title": "Report KPI block catalog",
        "acceptance_criteria": [
            "API returns list of available KPI blocks: gross revenue, net revenue, COGS, gross margin, profitability by product/dept, inventory turnover, variance plan-vs-actual, customer balance summary, top customers",
            "Each block has id, name, description, required filters",
            "FR-10.3 satisfied",
        ],
        "priority": "P1",
        "status": "📋 Planned",
        "labels": ["reports"],
    },
    {
        "id": "BC-1602",
        "epic_id": "BC-E16",
        "release": "R2",
        "title": "Custom report builder",
        "acceptance_criteria": [
            "User selects and combines KPI blocks into a named report",
            "Report supports date range + department + product + customer filters",
            "Saved reports retrievable by name",
            "FR-10.2 and FR-10.4 satisfied",
        ],
        "priority": "P1",
        "status": "📋 Planned",
        "labels": ["reports"],
    },
    {
        "id": "BC-1603",
        "epic_id": "BC-E16",
        "release": "R2",
        "title": "Advanced financial KPI computation",
        "acceptance_criteria": [
            "COGS = sum of FIFO-valued batch issues for period",
            "Gross margin = (revenue - COGS) / revenue",
            "Variance = (planned material qty - actual) per batch and per period",
            "Renders within 5 seconds for 12 months of data",
            "FR-10.3 satisfied",
        ],
        "priority": "P0",
        "status": "📋 Planned",
        "labels": ["reports", "finance"],
    },
    {
        "id": "BC-1604",
        "epic_id": "BC-E16",
        "release": "R2",
        "title": "Report export to Excel and PDF",
        "acceptance_criteria": [
            "GET /v2/reports/{id}/export?format=xlsx|pdf",
            "Excel: data table with filters applied",
            "PDF: formatted report with charts",
            "FR-10.6 satisfied",
        ],
        "priority": "P1",
        "status": "📋 Planned",
        "labels": ["reports"],
    },

    # ── BC-E17: Subscription Tier Management ─────────────
    {
        "id": "BC-1701",
        "epic_id": "BC-E17",
        "release": "R2",
        "title": "Super-admin subscription tier assignment",
        "acceptance_criteria": [
            "Super-admin can assign tier (Basic / Professional / Premium+AI) per tenant",
            "PUT /v2/admin/tenants/{id}/tier requires SUPER_ADMIN role",
            "FR-11.7 satisfied",
        ],
        "priority": "P1",
        "status": "📋 Planned",
        "labels": ["subscriptions", "admin"],
    },
    {
        "id": "BC-1702",
        "epic_id": "BC-E17",
        "release": "R2",
        "title": "Feature access enforcement by subscription tier",
        "acceptance_criteria": [
            "API endpoints restricted by tier (e.g. report constructor = Professional+)",
            "Accessing restricted feature returns 403 with tier message",
            "Enforcement implemented as cross-cutting concern (interceptor/filter)",
            "FR-11.7 satisfied",
        ],
        "priority": "P0",
        "status": "📋 Planned",
        "labels": ["subscriptions"],
    },

    # ══════════════════════════════════════════════════════
    #  RELEASE 3 — AI + Mobile
    # ══════════════════════════════════════════════════════

    # ── BC-E18: AI WhatsApp Order Intake ─────────────────
    {
        "id": "BC-1801",
        "epic_id": "BC-E18",
        "release": "R3",
        "title": "AI parse WhatsApp message to draft order",
        "acceptance_criteria": [
            "Incoming WhatsApp message processed by AI within 5 seconds",
            "Draft order created with extracted products, quantities, delivery time",
            "Confidence score returned with draft",
            "FR-12.1 and FR-1.2 (full AI) satisfied",
        ],
        "priority": "P0",
        "status": "📋 Planned",
        "labels": ["ai", "whatsapp"],
    },
    {
        "id": "BC-1802",
        "epic_id": "BC-E18",
        "release": "R3",
        "title": "AI two-way confirmation conversation",
        "acceptance_criteria": [
            "Bot handles multi-turn clarification on ambiguous items",
            "Bot handles lead time conflict resolution in conversation",
            "Customer explicit acceptance recorded before confirming",
            "FR-12.2 and FR-1.3 (full AI) satisfied",
        ],
        "priority": "P0",
        "status": "📋 Planned",
        "labels": ["ai", "whatsapp"],
    },
    {
        "id": "BC-1803",
        "epic_id": "BC-E18",
        "release": "R3",
        "title": "AI upsell suggestions (togglable per customer)",
        "acceptance_criteria": [
            "Bot offers relevant add-on products during conversation",
            "Upsell disabled if customer.upsellEnabled = false",
            "All AI suggestions advisory only — no auto-add without customer confirmation",
            "FR-12.1 and FR-1.4 satisfied",
        ],
        "priority": "P2",
        "status": "📋 Planned",
        "labels": ["ai", "whatsapp"],
    },
    {
        "id": "BC-1804",
        "epic_id": "BC-E18",
        "release": "R3",
        "title": "Human escalation trigger from AI bot",
        "acceptance_criteria": [
            "Customer request for human mid-conversation pauses bot",
            "In-app + WhatsApp alert sent to assigned operator",
            "Escalation logged with conversation context",
            "FR-1.5 (full AI) satisfied",
        ],
        "priority": "P2",
        "status": "📋 Planned",
        "labels": ["ai", "whatsapp"],
    },

    # ── BC-E19: AI Replenishment & Forecasting ───────────
    {
        "id": "BC-1901",
        "epic_id": "BC-E19",
        "release": "R3",
        "title": "AI replenishment hints",
        "acceptance_criteria": [
            "Weekly/monthly per-item replenishment hints displayed to warehouse manager",
            "Based on historical consumption rate and current stock level",
            "Hints are advisory — no auto-PO creation",
            "FR-12.3 satisfied",
        ],
        "priority": "P1",
        "status": "📋 Planned",
        "labels": ["ai", "inventory"],
    },
    {
        "id": "BC-1902",
        "epic_id": "BC-E19",
        "release": "R3",
        "title": "AI production planning suggestions",
        "acceptance_criteria": [
            "AI suggests optimal batch sizes and production sequencing",
            "Based on order history, trends, and department capacity",
            "Presented as suggestions alongside manual plan creation",
            "FR-12.4 satisfied",
        ],
        "priority": "P2",
        "status": "📋 Planned",
        "labels": ["ai", "production"],
    },
    {
        "id": "BC-1903",
        "epic_id": "BC-E19",
        "release": "R3",
        "title": "Demand forecasting per product per period",
        "acceptance_criteria": [
            "AI generates demand forecast for next week/month per product",
            "Displayed as planning aid on production dashboard",
            "Confidence score shown",
            "FR-12.7 satisfied",
        ],
        "priority": "P2",
        "status": "📋 Planned",
        "labels": ["ai", "forecasting"],
    },

    # ── BC-E20: AI Pricing & Anomaly ─────────────────────
    {
        "id": "BC-2001",
        "epic_id": "BC-E20",
        "release": "R3",
        "title": "AI pricing adjustment suggestions",
        "acceptance_criteria": [
            "AI suggests per-product or per-customer price adjustments",
            "Based on purchase volume, frequency, and margin data",
            "All suggestions advisory only — no auto-price changes",
            "FR-12.5 satisfied",
        ],
        "priority": "P2",
        "status": "📋 Planned",
        "labels": ["ai", "pricing"],
    },
    {
        "id": "BC-2002",
        "epic_id": "BC-E20",
        "release": "R3",
        "title": "AI report anomaly alerts",
        "acceptance_criteria": [
            "AI surfaces anomalies in reports: cost spikes, variance outliers, revenue drops",
            "Each alert has brief explanation and suggested action",
            "Alerts shown inline in report view",
            "FR-12.6 satisfied",
        ],
        "priority": "P2",
        "status": "📋 Planned",
        "labels": ["ai", "reports"],
    },

    # ── BC-E21: Driver Mobile App ─────────────────────────
    {
        "id": "BC-2101",
        "epic_id": "BC-E21",
        "release": "R3",
        "title": "Driver app real-time delivery tracking",
        "acceptance_criteria": [
            "Driver mobile app receives assigned delivery run",
            "Driver can view manifest and mark stops complete",
            "Real-time status updates visible to operator",
            "FR-7.7 satisfied",
        ],
        "priority": "P1",
        "status": "📋 Planned",
        "labels": ["mobile", "delivery"],
    },
    {
        "id": "BC-2102",
        "epic_id": "BC-E21",
        "release": "R3",
        "title": "Packaging confirmation in driver app",
        "acceptance_criteria": [
            "Driver confirms packaging checklist before departure",
            "Discrepancies flagged to operator",
            "FR-8.7 satisfied",
        ],
        "priority": "P2",
        "status": "📋 Planned",
        "labels": ["mobile", "delivery"],
    },
    {
        "id": "BC-2103",
        "epic_id": "BC-E21",
        "release": "R3",
        "title": "Driver on-spot payment collection (driver POS)",
        "acceptance_criteria": [
            "Driver app supports cash/card payment collection on delivery",
            "Receipt generated and synced to backend",
            "Payment recorded against invoice",
            "FR-8.7 and FR-8.8 satisfied",
        ],
        "priority": "P2",
        "status": "📋 Planned",
        "labels": ["mobile", "pos", "delivery"],
    },

    # ── BC-E22: Exchange Rate & Supplier API ─────────────
    {
        "id": "BC-2201",
        "epic_id": "BC-E22",
        "release": "R3",
        "title": "Exchange rate API integration",
        "acceptance_criteria": [
            "System pulls live exchange rates from configurable external API",
            "Rates stored per currency per date in exchange rate table",
            "Manual entry still supported as fallback",
            "FR-6.7 and FR-9.7 (API part) satisfied",
        ],
        "priority": "P2",
        "status": "📋 Planned",
        "labels": ["integrations", "finance"],
    },
    {
        "id": "BC-2202",
        "epic_id": "BC-E22",
        "release": "R3",
        "title": "Supplier API integration",
        "acceptance_criteria": [
            "Approved POs sent directly to configured supplier API endpoint",
            "Supports configurable per-supplier API credentials and format",
            "Falls back to manual/Excel export if API unavailable",
            "FR-6.4 (API part) satisfied",
        ],
        "priority": "P2",
        "status": "📋 Planned",
        "labels": ["integrations", "suppliers"],
    },

    # ── BC-E23: Mobile Customer App ───────────────────────
    {
        "id": "BC-2301",
        "epic_id": "BC-E23",
        "release": "R3",
        "title": "iOS/Android mobile customer app",
        "acceptance_criteria": [
            "Native iOS and Android app wrapping customer portal features",
            "Registration, login, catalog, order placement, order status, loyalty dashboard",
            "Push notifications for order status changes",
            "FR-2.1 (mobile) satisfied",
        ],
        "priority": "P2",
        "status": "📋 Planned",
        "labels": ["mobile", "customer-app"],
    },
]
