# ============================================================
#  BreadCost — JIRA Source Data
#  All epics and stories derived from work/120-task/JIRA.md
#  Structure: EPICS list + STORIES list
#
#  Epic keys: id, title, goal, sprint, requirements, release
#  Story keys: id, epic_id, title, acceptance_criteria (list),
#              priority, status, labels
# ============================================================

# ── PRIORITY MAP ────────────────────────────────────────────
# P0 = Highest, P1 = High, P2 = Medium, P3 = Low
PRIORITY_MAP = {
    "P0": "Highest",
    "P1": "High",
    "P2": "Medium",
    "P3": "Low",
}

# ── STATUS MAP ───────────────────────────────────────────────
# Maps JIRA.md status emoji to JIRA workflow status names
STATUS_MAP = {
    "✅ Done":    "Done",
    "🔄 In Progress": "In Progress",
    "📋 Planned": "To Do",
    "":           "To Do",
}

# ── EPICS ────────────────────────────────────────────────────
EPICS = [
    {
        "id": "BC-E00",
        "title": "User Journeys & End-to-End Flows",
        "goal": "Overarching reference epic. Documents all 62 named user flows (F1.1–F12.6) across all domains, cross-cutting all implementation epics. No code lives here — it is a traceability and alignment artifact.",
        "requirements": "All FRs across all domains",
        "release": "R1-R3",
        "labels": ["user-journey", "traceability"],
    },
    {
        "id": "BC-E01",
        "title": "Authentication & Authorization",
        "goal": "Secure login, JWT token management, and role enforcement across all endpoints.",
        "requirements": "FR-11.3, FR-11.4, NFR-G.4, NFR-G.5, NFR-G.6",
        "release": "R1",
        "labels": ["auth", "r1"],
    },
    {
        "id": "BC-E02",
        "title": "Order Management",
        "goal": "Full order lifecycle from creation through confirmation, cancellation, and status tracking.",
        "requirements": "FR-1.1, FR-1.6–FR-1.17",
        "release": "R1",
        "labels": ["orders", "r1"],
    },
    {
        "id": "BC-E03",
        "title": "Production Planning",
        "goal": "Plan creation, work order generation from confirmed orders, plan approval, and execution tracking.",
        "requirements": "FR-3.1–FR-3.10",
        "release": "R1",
        "labels": ["production", "r1"],
    },
    {
        "id": "BC-E04",
        "title": "Recipe & Product Management",
        "goal": "Recipe CRUD with versioning, ingredient management, technology steps, and product catalog.",
        "requirements": "FR-4.1–FR-4.9",
        "release": "R1",
        "labels": ["recipes", "products", "r1"],
    },
    {
        "id": "BC-E05",
        "title": "Inventory & Warehouse Management",
        "goal": "Lot-based receiving with FIFO cost tracking, transfers, adjustments, and stock alerts.",
        "requirements": "FR-5.1–FR-5.11",
        "release": "R1",
        "labels": ["inventory", "warehouse", "r1"],
    },
    {
        "id": "BC-E06",
        "title": "Point of Sale (POS)",
        "goal": "Walk-in B2C sales with cash/card payment, receipt data, and end-of-day reconciliation.",
        "requirements": "FR-8.1–FR-8.6",
        "release": "R1",
        "labels": ["pos", "r1"],
    },
    {
        "id": "BC-E07",
        "title": "Reporting & Dashboard",
        "goal": "Revenue summary, top products, production summary, and order summary for management decision-making.",
        "requirements": "FR-10.1, FR-10.4–FR-10.7",
        "release": "R1",
        "labels": ["reports", "dashboard", "r1"],
    },
    {
        "id": "BC-E08",
        "title": "User Management & Configuration",
        "goal": "Admin can manage staff accounts, roles, and tenant-wide settings.",
        "requirements": "FR-11.1–FR-11.9",
        "release": "R1",
        "labels": ["admin", "config", "r1"],
    },
    {
        "id": "BC-E09",
        "title": "Event Sourcing & Infrastructure",
        "goal": "All domain state changes recorded as immutable events with idempotency and CQRS projections.",
        "requirements": "NFR-G.10, NFR-G.11",
        "release": "R1",
        "labels": ["infrastructure", "event-sourcing", "r1"],
    },
    {
        "id": "BC-E10",
        "title": "Items & Raw Material Catalog",
        "goal": "Maintain a catalog of raw materials with units and stock thresholds.",
        "requirements": "FR-5.1",
        "release": "R1",
        "labels": ["items", "catalog", "r1"],
    },
    # ── Release 2 (planned) ───────────────────────────────
    {
        "id": "BC-E11",
        "title": "Customer Portal & Registration",
        "goal": "Web-based customer portal: registration, login, product catalog, order placement, real-time status.",
        "requirements": "FR-2.1–FR-2.5, FR-2.12",
        "release": "R2",
        "labels": ["customer-portal", "r2"],
    },
    {
        "id": "BC-E12",
        "title": "Loyalty Program",
        "goal": "Loyalty points, configurable tiers, tier benefits, point redemption at checkout.",
        "requirements": "FR-2.6–FR-2.11",
        "release": "R2",
        "labels": ["loyalty", "r2"],
    },
    {
        "id": "BC-E13",
        "title": "Supplier Management & PO Workflow",
        "goal": "Supplier catalog, PO suggestion, PO approval, Excel export, delivery matching, FX rates.",
        "requirements": "FR-6.1–FR-6.7",
        "release": "R2",
        "labels": ["suppliers", "procurement", "r2"],
    },
    {
        "id": "BC-E14",
        "title": "Delivery Management",
        "goal": "Delivery run assignment, manifests, driver completion, failed delivery, courier charges.",
        "requirements": "FR-7.1–FR-7.6",
        "release": "R2",
        "labels": ["delivery", "r2"],
    },
    {
        "id": "BC-E15",
        "title": "B2B Invoicing & Credit Control",
        "goal": "Invoices from delivered orders, payment terms, payment tracking, credit limit enforcement.",
        "requirements": "FR-9.8–FR-9.11",
        "release": "R2",
        "labels": ["invoicing", "finance", "r2"],
    },
    {
        "id": "BC-E16",
        "title": "Advanced Report Constructor",
        "goal": "User-configurable report builder with KPI blocks, advanced financial reports, export.",
        "requirements": "FR-10.2–FR-10.4",
        "release": "R2",
        "labels": ["reports", "r2"],
    },
    {
        "id": "BC-E17",
        "title": "Subscription Tier Management",
        "goal": "Super-admin assigns subscription tier per tenant; feature access enforced by tier.",
        "requirements": "FR-11.6–FR-11.7",
        "release": "R2",
        "labels": ["subscriptions", "r2"],
    },
    # ── Release 3 (planned) ───────────────────────────────
    {
        "id": "BC-E18",
        "title": "AI WhatsApp Order Intake",
        "goal": "Full AI-driven end-to-end WhatsApp order conversation: intent extraction, confirmation, upsell, conflict resolution.",
        "requirements": "FR-12.1, FR-12.2",
        "release": "R3",
        "labels": ["ai", "whatsapp", "r3"],
    },
    {
        "id": "BC-E19",
        "title": "AI Replenishment & Forecasting",
        "goal": "AI replenishment hints, production planning suggestions, and demand forecasting.",
        "requirements": "FR-12.3, FR-12.4, FR-12.7",
        "release": "R3",
        "labels": ["ai", "forecasting", "r3"],
    },
    {
        "id": "BC-E20",
        "title": "AI Pricing & Anomaly Alerts",
        "goal": "AI pricing suggestions and anomaly alerts in reports.",
        "requirements": "FR-12.5, FR-12.6",
        "release": "R3",
        "labels": ["ai", "pricing", "r3"],
    },
    {
        "id": "BC-E21",
        "title": "Driver Mobile App",
        "goal": "Driver app for real-time delivery tracking, packaging confirmation, on-spot payment collection.",
        "requirements": "FR-7.7, FR-8.7, FR-8.8",
        "release": "R3",
        "labels": ["mobile", "delivery", "r3"],
    },
    {
        "id": "BC-E22",
        "title": "Exchange Rate & Supplier API",
        "goal": "External exchange rate API and supplier API integrations.",
        "requirements": "FR-6.7, FR-9.7",
        "release": "R3",
        "labels": ["integrations", "r3"],
    },
    {
        "id": "BC-E23",
        "title": "Mobile Customer App",
        "goal": "iOS/Android customer app (mobile extension of the customer portal).",
        "requirements": "FR-2.1 (mobile)",
        "release": "R3",
        "labels": ["mobile", "customer-app", "r3"],
    },
]

# ── STORIES ──────────────────────────────────────────────────
STORIES = [
    # ── BC-E01: Auth ─────────────────────────────────────
    {
        "id": "BC-101",
        "epic_id": "BC-E01",
        "title": "User login with JWT",
        "acceptance_criteria": [
            "POST /v1/auth/login accepts {username, password}",
            "Returns JWT token, username, roles, tenantId",
            "Invalid credentials return 401",
            "Blank fields return 400",
        ],
        "priority": "P0",
        "status": "✅ Done",
        "labels": ["auth"],
    },
    {
        "id": "BC-102",
        "epic_id": "BC-E01",
        "title": "JWT authentication filter",
        "acceptance_criteria": [
            "All /v1/** endpoints require Bearer token",
            "Invalid/expired token returns 401",
            "Token contains username, roles, tenantId claims",
        ],
        "priority": "P0",
        "status": "✅ Done",
        "labels": ["auth"],
    },
    {
        "id": "BC-103",
        "epic_id": "BC-E01",
        "title": "Role-based method security",
        "acceptance_criteria": [
            "@PreAuthorize on every controller method",
            "Unauthorized role returns 403",
            "Matches role access matrix in MANUAL_TEST_PLAN.md Section 12",
        ],
        "priority": "P0",
        "status": "✅ Done",
        "labels": ["auth", "roles"],
    },
    {
        "id": "BC-104",
        "epic_id": "BC-E01",
        "title": "Password hashing with BCrypt",
        "acceptance_criteria": [
            "Passwords stored as BCrypt hashes",
            "Raw passwords never stored or logged",
        ],
        "priority": "P0",
        "status": "✅ Done",
        "labels": ["auth", "security"],
    },
    {
        "id": "BC-105",
        "epic_id": "BC-E01",
        "title": "Deactivated user cannot login",
        "acceptance_criteria": [
            "User with active=false receives 401 'Account is deactivated'",
        ],
        "priority": "P1",
        "status": "✅ Done",
        "labels": ["auth"],
    },
    # ── BC-E02: Orders ───────────────────────────────────
    {
        "id": "BC-201",
        "epic_id": "BC-E02",
        "title": "Create DRAFT order",
        "acceptance_criteria": [
            "POST /v1/orders creates order with status=DRAFT",
            "Requires tenantId, at least 1 line item",
            "Returns 201 with orderId",
            "Only Admin, ProductionUser can create",
        ],
        "priority": "P0",
        "status": "✅ Done",
        "labels": ["orders"],
    },
    {
        "id": "BC-202",
        "epic_id": "BC-E02",
        "title": "List orders with filters",
        "acceptance_criteria": [
            "GET /v1/orders?tenantId=&status= returns array",
            "Filters by status, customerId",
            "Empty filters return all",
            "Role-restricted",
        ],
        "priority": "P0",
        "status": "✅ Done",
        "labels": ["orders"],
    },
    {
        "id": "BC-203",
        "epic_id": "BC-E02",
        "title": "Get order by ID",
        "acceptance_criteria": [
            "GET /v1/orders/{id}?tenantId= returns full order with lines",
            "404 if not found",
        ],
        "priority": "P1",
        "status": "✅ Done",
        "labels": ["orders"],
    },
    {
        "id": "BC-204",
        "epic_id": "BC-E02",
        "title": "Confirm order (DRAFT→CONFIRMED)",
        "acceptance_criteria": [
            "POST /v1/orders/{id}/confirm transitions DRAFT→CONFIRMED",
            "Sets confirmedAt timestamp",
            "Emits OrderConfirmedEvent",
            "Rejects non-DRAFT orders with 409",
        ],
        "priority": "P0",
        "status": "✅ Done",
        "labels": ["orders", "state-machine"],
    },
    {
        "id": "BC-205",
        "epic_id": "BC-E02",
        "title": "Cancel order",
        "acceptance_criteria": [
            "POST /v1/orders/{id}/cancel?reason= transitions to CANCELLED",
            "Requires reason parameter",
            "Only cancellable from DRAFT or CONFIRMED",
            "Emits OrderCancelledEvent",
        ],
        "priority": "P0",
        "status": "✅ Done",
        "labels": ["orders", "state-machine"],
    },
    {
        "id": "BC-206",
        "epic_id": "BC-E02",
        "title": "Status transition enforcement",
        "acceptance_criteria": [
            "Invalid transitions (e.g. CANCELLED→CONFIRMED) return 409",
            "Double-confirm returns 409",
        ],
        "priority": "P0",
        "status": "✅ Done",
        "labels": ["orders", "state-machine"],
    },
    {
        "id": "BC-207",
        "epic_id": "BC-E02",
        "title": "Rush order support",
        "acceptance_criteria": [
            "forceRush=true creates rush order",
            "Custom premium % can be set via customRushPremiumPct",
        ],
        "priority": "P2",
        "status": "✅ Done",
        "labels": ["orders", "rush"],
    },
    {
        "id": "BC-208",
        "epic_id": "BC-E02",
        "title": "Order status advance",
        "acceptance_criteria": [
            "POST /v1/orders/{id}/status?targetStatus= advances order (IN_PRODUCTION, READY, DELIVERED)",
        ],
        "priority": "P1",
        "status": "✅ Done",
        "labels": ["orders", "state-machine"],
    },
    # ── BC-E03: Production Planning ──────────────────────
    {
        "id": "BC-301",
        "epic_id": "BC-E03",
        "title": "Create production plan",
        "acceptance_criteria": [
            "POST /v1/production-plans with date, shift, tenantId",
            "Returns 201 with planId, status=DRAFT",
        ],
        "priority": "P0",
        "status": "✅ Done",
        "labels": ["production"],
    },
    {
        "id": "BC-302",
        "epic_id": "BC-E03",
        "title": "Generate work orders",
        "acceptance_criteria": [
            "POST /plans/{id}/generate creates WOs from confirmed orders",
            "Plan status → GENERATED",
            "Each WO has product, target qty, department",
        ],
        "priority": "P0",
        "status": "✅ Done",
        "labels": ["production"],
    },
    {
        "id": "BC-303",
        "epic_id": "BC-E03",
        "title": "Approve plan",
        "acceptance_criteria": [
            "POST /plans/{id}/approve transitions GENERATED→APPROVED",
            "Only Admin, ProductionUser can approve",
        ],
        "priority": "P0",
        "status": "✅ Done",
        "labels": ["production"],
    },
    {
        "id": "BC-304",
        "epic_id": "BC-E03",
        "title": "Start and complete plan lifecycle",
        "acceptance_criteria": [
            "Start: APPROVED→IN_PROGRESS",
            "Complete: IN_PROGRESS→COMPLETED",
        ],
        "priority": "P1",
        "status": "✅ Done",
        "labels": ["production", "state-machine"],
    },
    {
        "id": "BC-305",
        "epic_id": "BC-E03",
        "title": "Work order lifecycle",
        "acceptance_criteria": [
            "Start WO: PLANNED→IN_PROGRESS",
            "Complete WO: IN_PROGRESS→COMPLETED",
            "Cancel WO: any→CANCELLED",
        ],
        "priority": "P0",
        "status": "✅ Done",
        "labels": ["production", "state-machine"],
    },
    {
        "id": "BC-306",
        "epic_id": "BC-E03",
        "title": "Material requirements view",
        "acceptance_criteria": [
            "GET /plans/{id}/material-requirements returns ingredient needs based on recipes",
        ],
        "priority": "P2",
        "status": "✅ Done",
        "labels": ["production", "inventory"],
    },
    {
        "id": "BC-307",
        "epic_id": "BC-E03",
        "title": "Plan schedule and WO scheduling",
        "acceptance_criteria": [
            "GET /plans/{id}/schedule returns timeline",
            "PATCH /work-orders/{id}/schedule adjusts start/duration",
        ],
        "priority": "P2",
        "status": "✅ Done",
        "labels": ["production"],
    },
    {
        "id": "BC-308",
        "epic_id": "BC-E03",
        "title": "List work orders by department",
        "acceptance_criteria": [
            "GET /work-orders?tenantId=&departmentId= returns filtered WOs",
        ],
        "priority": "P1",
        "status": "✅ Done",
        "labels": ["production"],
    },
    # ── BC-E04: Recipe & Product ─────────────────────────
    {
        "id": "BC-401",
        "epic_id": "BC-E04",
        "title": "Create recipe with ingredients",
        "acceptance_criteria": [
            "POST /v1/recipes with ingredients array",
            "Returns 201 with version number",
            "Only Admin, Technologist can create",
        ],
        "priority": "P0",
        "status": "✅ Done",
        "labels": ["recipes"],
    },
    {
        "id": "BC-402",
        "epic_id": "BC-E04",
        "title": "Recipe versioning",
        "acceptance_criteria": [
            "Multiple recipes per product, each with version number",
            "GET /v1/recipes?productId= returns version history",
        ],
        "priority": "P1",
        "status": "✅ Done",
        "labels": ["recipes"],
    },
    {
        "id": "BC-403",
        "epic_id": "BC-E04",
        "title": "Activate recipe",
        "acceptance_criteria": [
            "POST /recipes/{id}/activate sets as active for product",
            "Archives previous active version",
        ],
        "priority": "P0",
        "status": "✅ Done",
        "labels": ["recipes"],
    },
    {
        "id": "BC-404",
        "epic_id": "BC-E04",
        "title": "Get active recipe",
        "acceptance_criteria": [
            "GET /v1/recipes/active?productId= returns current active recipe",
        ],
        "priority": "P1",
        "status": "✅ Done",
        "labels": ["recipes"],
    },
    {
        "id": "BC-405",
        "epic_id": "BC-E04",
        "title": "Update recipe ingredients",
        "acceptance_criteria": [
            "PUT /recipes/{id}/ingredients replaces ingredient list",
        ],
        "priority": "P1",
        "status": "✅ Done",
        "labels": ["recipes"],
    },
    {
        "id": "BC-406",
        "epic_id": "BC-E04",
        "title": "Material requirements calculation",
        "acceptance_criteria": [
            "GET /recipes/{id}/material-requirements?batchMultiplier= returns per-ingredient quantities needed",
        ],
        "priority": "P2",
        "status": "✅ Done",
        "labels": ["recipes", "inventory"],
    },
    {
        "id": "BC-407",
        "epic_id": "BC-E04",
        "title": "Technology steps CRUD",
        "acceptance_criteria": [
            "Create step: POST /v1/technology-steps",
            "Edit: PUT /technology-steps/{id}",
            "Delete: DELETE /technology-steps/{id}",
            "List: GET /technology-steps?recipeId= ordered by stepNumber",
        ],
        "priority": "P1",
        "status": "✅ Done",
        "labels": ["recipes", "tech-steps"],
    },
    {
        "id": "BC-408",
        "epic_id": "BC-E04",
        "title": "Product CRUD",
        "acceptance_criteria": [
            "List: GET /v1/products",
            "Create: POST /v1/products (201)",
            "Update: PUT /products/{id}",
            "Sale unit: PIECE/WEIGHT/BOTH",
        ],
        "priority": "P0",
        "status": "✅ Done",
        "labels": ["products"],
    },
    # ── BC-E05: Inventory ────────────────────────────────
    {
        "id": "BC-501",
        "epic_id": "BC-E05",
        "title": "Receive lot (stock receipt)",
        "acceptance_criteria": [
            "POST /v1/inventory/receipts records lot with cost",
            "Emits ReceiveLotEvent",
            "Idempotent via idempotencyKey",
            "Only Admin, Warehouse can receive",
        ],
        "priority": "P0",
        "status": "✅ Done",
        "labels": ["inventory"],
    },
    {
        "id": "BC-502",
        "epic_id": "BC-E05",
        "title": "View inventory positions",
        "acceptance_criteria": [
            "GET /v1/inventory/positions returns on-hand qty per item per site",
            "Filter by siteId",
        ],
        "priority": "P0",
        "status": "✅ Done",
        "labels": ["inventory"],
    },
    {
        "id": "BC-503",
        "epic_id": "BC-E05",
        "title": "Inventory transfer",
        "acceptance_criteria": [
            "POST /v1/inventory/transfers moves qty between locations",
            "Emits TransferInventoryEvent",
            "Idempotent",
        ],
        "priority": "P1",
        "status": "✅ Done",
        "labels": ["inventory"],
    },
    {
        "id": "BC-504",
        "epic_id": "BC-E05",
        "title": "Inventory adjustment",
        "acceptance_criteria": [
            "POST /v1/inventory/adjust with reason code (WASTE/SPOILAGE/COUNT_CORRECTION/OTHER)",
            "Positive or negative qty",
        ],
        "priority": "P1",
        "status": "✅ Done",
        "labels": ["inventory"],
    },
    {
        "id": "BC-505",
        "epic_id": "BC-E05",
        "title": "Issue to batch (material consumption)",
        "acceptance_criteria": [
            "POST /v1/batches/{id}/issues issues material to production batch",
            "FIFO lot selection",
            "Emits IssueToBatchEvent",
        ],
        "priority": "P0",
        "status": "✅ Done",
        "labels": ["inventory", "production"],
    },
    {
        "id": "BC-506",
        "epic_id": "BC-E05",
        "title": "Stock alerts",
        "acceptance_criteria": [
            "GET /v1/inventory/alerts returns items below minStockThreshold",
            "Each alert: itemId, onHandQty, minThreshold, severity",
        ],
        "priority": "P1",
        "status": "✅ Done",
        "labels": ["inventory", "alerts"],
    },
    {
        "id": "BC-507",
        "epic_id": "BC-E05",
        "title": "Idempotency enforcement",
        "acceptance_criteria": [
            "Resending receipt/transfer with same idempotencyKey does not duplicate",
            "Returns success without re-processing",
        ],
        "priority": "P0",
        "status": "✅ Done",
        "labels": ["inventory", "idempotency"],
    },
    # ── BC-E06: POS ──────────────────────────────────────
    {
        "id": "BC-601",
        "epic_id": "BC-E06",
        "title": "Create POS sale (CASH)",
        "acceptance_criteria": [
            "POST /v1/pos/sales with paymentMethod=CASH",
            "Calculates totalAmount, changeGiven",
            "Returns 201 with saleId, status=COMPLETED",
            "Records cashierId from JWT",
        ],
        "priority": "P0",
        "status": "✅ Done",
        "labels": ["pos"],
    },
    {
        "id": "BC-602",
        "epic_id": "BC-E06",
        "title": "Create POS sale (CARD)",
        "acceptance_criteria": [
            "paymentMethod=CARD, cardReference required",
            "changeGiven=0",
            "Returns 201",
        ],
        "priority": "P0",
        "status": "✅ Done",
        "labels": ["pos"],
    },
    {
        "id": "BC-603",
        "epic_id": "BC-E06",
        "title": "List POS sales",
        "acceptance_criteria": [
            "GET /v1/pos/sales?tenantId= returns sale history",
            "Filter by date",
        ],
        "priority": "P1",
        "status": "✅ Done",
        "labels": ["pos"],
    },
    {
        "id": "BC-604",
        "epic_id": "BC-E06",
        "title": "End-of-day reconciliation",
        "acceptance_criteria": [
            "POST /v1/pos/reconcile returns cash/card totals, refunds, net sales",
            "Grouped by date",
        ],
        "priority": "P1",
        "status": "✅ Done",
        "labels": ["pos"],
    },
    {
        "id": "BC-605",
        "epic_id": "BC-E06",
        "title": "POS input validation",
        "acceptance_criteria": [
            "Empty lines → 400",
            "Missing payment method → 400",
        ],
        "priority": "P1",
        "status": "✅ Done",
        "labels": ["pos"],
    },
    {
        "id": "BC-606",
        "epic_id": "BC-E06",
        "title": "POS role enforcement",
        "acceptance_criteria": [
            "Only Admin, Cashier can create sales",
            "Warehouse, Finance, Production → 403",
        ],
        "priority": "P0",
        "status": "✅ Done",
        "labels": ["pos", "roles"],
    },
    # ── BC-E07: Reports ──────────────────────────────────
    {
        "id": "BC-701",
        "epic_id": "BC-E07",
        "title": "Revenue summary report",
        "acceptance_criteria": [
            "GET /reports/revenue-summary returns today/week/month/allTime revenue",
            "Includes currency",
            "Accessible to Admin, FinanceUser, Viewer",
        ],
        "priority": "P0",
        "status": "✅ Done",
        "labels": ["reports"],
    },
    {
        "id": "BC-702",
        "epic_id": "BC-E07",
        "title": "Top products report",
        "acceptance_criteria": [
            "GET /reports/top-products?limit=N returns ranked products",
            "Each entry: productName, totalQty, totalRevenue",
        ],
        "priority": "P1",
        "status": "✅ Done",
        "labels": ["reports"],
    },
    {
        "id": "BC-703",
        "epic_id": "BC-E07",
        "title": "Production summary report",
        "acceptance_criteria": [
            "GET /reports/production-summary returns plan counts by status, WO completion rate",
            "Date range filter supported",
        ],
        "priority": "P1",
        "status": "✅ Done",
        "labels": ["reports"],
    },
    {
        "id": "BC-704",
        "epic_id": "BC-E07",
        "title": "Orders summary report",
        "acceptance_criteria": [
            "GET /reports/orders-summary returns today count, value, breakdown by status",
        ],
        "priority": "P1",
        "status": "✅ Done",
        "labels": ["reports"],
    },
    {
        "id": "BC-705",
        "epic_id": "BC-E07",
        "title": "Report role enforcement",
        "acceptance_criteria": [
            "Admin, FinanceUser, Viewer can access",
            "Cashier → 403",
        ],
        "priority": "P0",
        "status": "✅ Done",
        "labels": ["reports", "roles"],
    },
    # ── BC-E08: Admin & Config ───────────────────────────
    {
        "id": "BC-801",
        "epic_id": "BC-E08",
        "title": "List users",
        "acceptance_criteria": [
            "GET /v1/users?tenantId= returns user list",
            "Password hashes masked",
            "Admin only",
        ],
        "priority": "P0",
        "status": "✅ Done",
        "labels": ["admin", "users"],
    },
    {
        "id": "BC-802",
        "epic_id": "BC-E08",
        "title": "Create user",
        "acceptance_criteria": [
            "POST /v1/users with username, password, roles",
            "Returns 201",
            "New user can log in",
            "Duplicate username → 409",
        ],
        "priority": "P0",
        "status": "✅ Done",
        "labels": ["admin", "users"],
    },
    {
        "id": "BC-803",
        "epic_id": "BC-E08",
        "title": "Update user roles",
        "acceptance_criteria": [
            "PUT /v1/users/{id} updates roles, displayName, department",
            "Changes take effect on next login",
        ],
        "priority": "P1",
        "status": "✅ Done",
        "labels": ["admin", "users", "roles"],
    },
    {
        "id": "BC-804",
        "epic_id": "BC-E08",
        "title": "Deactivate user",
        "acceptance_criteria": [
            "PUT /v1/users/{id} with active:false",
            "Deactivated user cannot log in (401)",
        ],
        "priority": "P1",
        "status": "✅ Done",
        "labels": ["admin", "users"],
    },
    {
        "id": "BC-805",
        "epic_id": "BC-E08",
        "title": "Reset password",
        "acceptance_criteria": [
            "POST /v1/users/{id}/reset-password",
            "Old password stops working, new one works",
        ],
        "priority": "P1",
        "status": "✅ Done",
        "labels": ["admin", "users"],
    },
    {
        "id": "BC-806",
        "epic_id": "BC-E08",
        "title": "Department CRUD",
        "acceptance_criteria": [
            "Create: POST /v1/departments (201)",
            "List: GET /v1/departments",
            "Update: PUT /departments/{id}",
            "Admin only",
        ],
        "priority": "P1",
        "status": "✅ Done",
        "labels": ["admin", "departments"],
    },
    {
        "id": "BC-807",
        "epic_id": "BC-E08",
        "title": "Tenant config management",
        "acceptance_criteria": [
            "GET /v1/config returns cutoff time, rush premium, currency",
            "PUT /v1/config updates settings",
            "Admin only for writes",
        ],
        "priority": "P1",
        "status": "✅ Done",
        "labels": ["admin", "config"],
    },
    # ── BC-E09: Event Sourcing ───────────────────────────
    {
        "id": "BC-901",
        "epic_id": "BC-E09",
        "title": "Event store implementation",
        "acceptance_criteria": [
            "Append-only event store",
            "Events: ReceiveLot, IssueToBatch, TransferInventory, OrderCreated/Confirmed/Cancelled, CloseBatch, etc.",
            "Each event has idempotencyKey, occurredAtUtc, tenantId",
        ],
        "priority": "P0",
        "status": "✅ Done",
        "labels": ["infrastructure", "event-sourcing"],
    },
    {
        "id": "BC-902",
        "epic_id": "BC-E09",
        "title": "Idempotency service",
        "acceptance_criteria": [
            "Duplicate idempotencyKey detected and rejected",
            "Command handler returns success without re-executing",
        ],
        "priority": "P0",
        "status": "✅ Done",
        "labels": ["infrastructure", "idempotency"],
    },
    {
        "id": "BC-903",
        "epic_id": "BC-E09",
        "title": "Inventory projection",
        "acceptance_criteria": [
            "Reads events to build on-hand positions",
            "FIFO cost layers maintained per lot",
        ],
        "priority": "P0",
        "status": "✅ Done",
        "labels": ["infrastructure", "inventory"],
    },
    {
        "id": "BC-904",
        "epic_id": "BC-E09",
        "title": "Global exception handler",
        "acceptance_criteria": [
            "IllegalArgumentException → 400",
            "AccessDeniedException → 403",
            "IllegalStateException → 409",
            "DataIntegrityViolationException → 409",
            "Unhandled → 500",
        ],
        "priority": "P0",
        "status": "✅ Done",
        "labels": ["infrastructure"],
    },
    # ── BC-E10: Items ────────────────────────────────────
    {
        "id": "BC-1001",
        "epic_id": "BC-E10",
        "title": "Item CRUD",
        "acceptance_criteria": [
            "Create: POST /v1/items (201)",
            "List: GET /v1/items?type=&activeOnly=",
            "Update: PUT /items/{id}",
            "Fields: name, type, baseUom, minStockThreshold",
        ],
        "priority": "P0",
        "status": "✅ Done",
        "labels": ["items"],
    },
    {
        "id": "BC-1002",
        "epic_id": "BC-E10",
        "title": "Item types",
        "acceptance_criteria": [
            "Supports INGREDIENT, PACKAGING, FG, BYPRODUCT, WIP",
            "Filter by type query param",
        ],
        "priority": "P1",
        "status": "✅ Done",
        "labels": ["items"],
    },
]
